# Generated by Django 3.2.6 on 2022-05-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pylonapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seedphrase',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
